# Generated by Django 4.0.6 on 2022-07-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_alter_snack_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.TextField(default='Add you notes,please!', max_length=200),
        ),
    ]
